version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "85:80"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: jonnik_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jonnik_app_bd
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_SSL: "false"  # Desactiva SSL
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: